apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-go
  namespace: ai-platform
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: api-go
  namespaceSelector:
    matchNames:
      - ai-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s