apiVersion: ENC[AES256_GCM,data:jCs=,iv:SZEIuZlK28M0lkYqIPcxjkL0vitP8SkQzwxeTxgxcqU=,tag:tBEgP0yPzNWuC27EvVefDg==,type:str]
kind: ENC[AES256_GCM,data:Xv/iR2dM,iv:7nlQW6k9oVpGNBB22AyrxynCwAofiSHKZubLZpjCZJg=,tag:AciRWp792zrk72ulGcscRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ItiIZDDH/7bT9xkNdsrqBONX33ZbbKARtg==,iv:GjvNW9X2GYoU33B8UryWGbmTuljKIfUTZ++fobSeckQ=,tag:NRyonW34RSsBrbWB5w2BMQ==,type:str]
    namespace: ENC[AES256_GCM,data:EQV7Wakf7zKD4Q==,iv:h/Ati76TWA1BvtCZMmyJ4DDfz1hYcPX1fseQEAXZyNA=,tag:fGA99OeOVD99y6YGN3VZwQ==,type:str]
type: ENC[AES256_GCM,data:2Z3EqmYV,iv:NYObOH0wHjYYcCFUmc1aCpnyeAy7ixv8qqb9VSADsFk=,tag:00oAqySIyBiYJqpn+R+BVA==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:f00ASn4=,iv:2TSR+tHKQwIazhFp39kYwwkXgX533iEL+JmcsHx+dro=,tag:UZNx32EBi74jaiyWFqN5BQ==,type:str]
    admin-password: ENC[AES256_GCM,data:azbsFWA9Oe85Cobo,iv:1Yqf0A73s0DIYFJGO7VH5gbDMpxHC/+gh2O9CJbuzv4=,tag:D6HJQksxb/vklsI63unc6A==,type:str]
sops:
    age:
        - recipient: age1vu0xz5gs5rtlqme4hvz7uclnq7zcxafmhr0qcwa52wzcfq79qgdsl8g9dv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV1FPcWROMGRlcnY4eHJU
            WlJQdUk5am1kNzNCYVJNckVoNHNJaTJwMmhRCjIrUkNMU2NTb3YxZk9XSmZyenJR
            N0xmTDJPS3JDMk1ZWXNOOVlxdTMwVlkKLS0tIEFYdDJpa3lYdlVWMmNzL1I4aVpP
            R01kc3pyMEdsZDE5ZU5mUUZBMUpaQTQK5L5TghVamJKB5n1mZxOvL6O7HekDxj7n
            UFBGS6GXJ1ASStHcmFpecv0UUwZQsmAtKzjdEMI28NUO2bWADihpYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T09:14:13Z"
    mac: ENC[AES256_GCM,data:Fo1+yCmWRnF/0LhirrpEvSqF5lBE8Mo/7oz/UBVFlk5FF+jAqYkc/cKJt8RWTf5K0iAzvNGU9ip6xOwB8yLN2GqABh+wzb5nVVn3iz+Ij2aYqLfGsDQpBybEMbJBUd/h8wl0zhYmh8WKxD9E7d3DYNRGW/ryKGoLJz23dE+Dmak=,iv:u87Im5cN5d4ztNkmWQE4QCouRKS3ZUZEYeCjs6Jow+g=,tag:9v+HPAb6wNSVooMqJp8J5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
