apiVersion: ENC[AES256_GCM,data:1mE=,iv:XUPJglwXGEXNqEhETm0f9KO6JX7jjDRIrBnVAKEbfaM=,tag:1jHkgjBeyJn0iKHc2Fd0yg==,type:str]
kind: ENC[AES256_GCM,data:uJm80nZw,iv:b+Dp6tWdb/0C6gbPfIEo8XmMoaBJrysqirBgJy4Pd4g=,tag:KEzAUqXfuJf5HPlKr+DRsg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p0xmPXJUIaezo6t768+Jjqwn3y/Ahi8vHg==,iv:y+PkuOljlaCIrXvlfIlbeNcpge+hklaaFKbsqWMgksQ=,tag:7Bdfp144IMSYTyRHcwBBvQ==,type:str]
    namespace: ENC[AES256_GCM,data:W3D9vTBPPZw4m44=,iv:zg3hhcL2bCn/E/MoU7BvzARO45IVmH5kPVedyFs3bMo=,tag:6Ocxod+kNTcPwZdgtMC2zQ==,type:str]
type: ENC[AES256_GCM,data:4SejCeIu,iv:4GbzB2k4T72JK5HlBQixKM1X41bTkuORBzWLgeF6Kgc=,tag:iUkQdXd73q+JQl/ZUz2Dkg==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:bmjnY8c=,iv:l3Se/QUIctW6szA864iuU3TnfS8gx5gOkWuyquf8yDA=,tag:HYNU0z3TjSOiECh1G+NAvw==,type:str]
    admin-password: ENC[AES256_GCM,data:tWQtRGaNUlydAzQK,iv:9YydnBA/V0qtzbGrU7mHhW0DI9tYmLUxXl8eRKjJatc=,tag:HQqxQ9RaKGVcjLu/46uSFw==,type:str]
sops:
    age:
        - recipient: age1vu0xz5gs5rtlqme4hvz7uclnq7zcxafmhr0qcwa52wzcfq79qgdsl8g9dv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VnlNWWJwTVF2ZGV6R2FG
            Z05STjVnUnVtWUpGUUg4eUM4ZTlPTHNHSm5JCkE3czl6OHlSZS9xcFI1cXhZNkp4
            c3hqZDFMNU96ZnNnYWNjOEovVk0yMEkKLS0tIDJaKzI2d0FtdUxVYTlTWmtHWjBn
            dndiTGNPUEZveG9seGpOalBxb0tvZnMKqe/Jqn0k4R6D2XkzjfeeHWjSlSw2SI2x
            W9it6Ndx2UioODpqfbR83ag/nNTITCY7uPL+iiyHW08XKXIOriZFMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T12:06:27Z"
    mac: ENC[AES256_GCM,data:tQbLK+KEhasFkk0l375nVXslnT8zGw4rpfYpObN242z+ANljUjmuH5HkpZs49fLSqmxx89lfEh3Qb5+CaHYrjXUXF/mNLv6M4Wiknv93C8BnWq8gA7m7ZZzhNPAT/U9qhwTzhSCmLfKw0Z0cjlzl1hC8p+4qI4EuU8ydwLRiyTM=,iv:uCNVljW6RPXYPrL+jlGMVfsx5a9Q1/t53M/jrYi0/84=,tag:OYS/9Al15MvwyA4hNn0EgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
