apiVersion: ENC[AES256_GCM,data:afo=,iv:xxUkbVVGfBS4OU98EZE1S9ZnWdQL+N1mODudNl77/QE=,tag:pvjCDNrSLM4AL7AVeXDRgQ==,type:str]
kind: ENC[AES256_GCM,data:6MoNwc+V,iv:hgS/3LtTc3H/FzihQk2Td4JBVlABatDkfBtzL4zjErg=,tag:XKfAzYY+1YaqJMG4ZSlZLg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:G9R8xBYahOFvtVkRMow=,iv:iuZdgU8fyqwW6lg+/jVRMORo+uwrAHuvlIGmBWTrVZY=,tag:RwsrsM92KmTt5aofJIHHow==,type:str]
    namespace: ENC[AES256_GCM,data:XrTDDpsnAc77G9A=,iv:kLDvJJ0gZhbR4c1+gsfaledF9TYbBNVYz6g5KzjpoIY=,tag:Y0d5dTO1aR407z2jmPxtMQ==,type:str]
type: ENC[AES256_GCM,data:t+X/7a16,iv:s7dwnOmxUMEXsoxw0I64Rs2s/mddoF3FCdWI8W0hD+E=,tag:cpxMOdwx0qIA7+Ca4niN8w==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:WZ3rYaSR2tlFW3Tr7H4npEkUdNa3g06wXgUgeELilvY=,iv:TMpn6cEvptP0Vghuxx8h6uztXerfWLXB2Gc40+Ah0F0=,tag:IUnaFePelI3P7StaAr5eNw==,type:str]
sops:
    age:
        - recipient: age1vu0xz5gs5rtlqme4hvz7uclnq7zcxafmhr0qcwa52wzcfq79qgdsl8g9dv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOStuYXNPeDVJSXduaUdp
            ZFlRcHZ1ZFYzbG5DZUNqbjVmUy9lK0FsZ21nClQrSWNxVzdSNVQwaGJDbG1qby96
            dU9tMUFUQUw3aU1od3JOMkliL011eE0KLS0tIDNLbHlMczVFSVhhNXdZYlBGcG9w
            VlZvMTNHVjNITXlUTk11NGhhYWNPTncK1jrsAStqpXZx3ZPTKeOm2Sl/wopmToqX
            VVUUBjOLRcQgzLGaEce4aA+8aqgOaGp219wScEAVEYdLFYwSzuAp6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T15:17:09Z"
    mac: ENC[AES256_GCM,data:L0yn9Llx7qxZQ7I4QvmQZCy1RoS63jA9f9Ps8mkB0Exh7Lakm24CsW0eTYGDFRGRJwsIQx79Id4MaaWSm5G7Gpw50lCW3BDL6RsAAFDylQqz5AtCxwkfoxlwqU96Z+V+xGZ+YskdR3lBU0izBSs8snC30HDSydXpu7fAlWQteQo=,iv:kRQ0fES/aADMSNCIQhAyOFj0gyR2GLdU2olHAdySxbY=,tag:/KoS3kAVvKa8vAIMklX04Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
