apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web3-infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kirill140992/ai-inference-platform.git'
    targetRevision: HEAD
    path: k8s/web3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true